
[[_usage]]
= Usage

== Script Variables
The following variables are available by default:

|===
|Name |Type |Description

|`ctx`
|`io.micronaut.context.ApplicationContext`
|The application context

|`user`
|`com.agorapulse.micronaut.console.User`
|The user executing the script

|`request`
|`io.micronaut.http.HttpRequest`
|The request used to execute the script (only for HTTP calls)

|===

You can create additional beans that implement `com.agorapulse.micronaut.console.BindingProvider` to provide additional binding variables.

You can see what bindings are available in your application by issuing a `GET` request to `/console/dsl/text`:

[source, shell script]
----
curl http://localhost:8080/console/dsl/text
----

You can download an up-to-date DSL file from your server by altering the `text` part of the path. These are the available descriptors:

* `gdsl` for Groovy and IntelliJ
* `dsld` for Groovy and Eclipse

[source,shell script]
----
 curl http://localhost:8080/console/dsl/gdsl > console.gdsl
----

== Serverless Functions

You can use Micronaut Console to create a sandbox function to execute arbitrary code on AWS Lambda or similar serverless function platforms.

Add the following to an existing or new Micronaut function:

[source, groovy, role="primary"]
.Basic
----
include::{root-dir}/examples/micronaut-console-example-function/micronaut-console-example-function.gradle[tags=import-runtime]
include::{root-dir}/examples/micronaut-console-example-function/micronaut-console-example-function.gradle[tags=import]

include::{root-dir}/examples/micronaut-console-example-function/micronaut-console-example-function.gradle[tags=tasks]
----

[source, groovy, role="secondary"]
.Authorized
----
include::{root-dir}/examples/micronaut-console-example-function/micronaut-console-example-function.gradle[tags=import-runtime]
include::{root-dir}/examples/micronaut-console-example-function/micronaut-console-example-function.gradle[tags=import-sts]
include::{root-dir}/examples/micronaut-console-example-function/micronaut-console-example-function.gradle[tags=import]

include::{root-dir}/examples/micronaut-console-example-function/micronaut-console-example-function.gradle[tags=auth]
----

Then you can invoke the function from the command line as follows (assuming you have set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY` environment variables)

[source,shell script]
----
./gradlew invokeSanbox -Pscript.file path/to/script.groovy
----

You should use a lambda role restricted to what you are planning to do with the sandbox function to maximize the security.

== Server Applications

The typical use case is to execute a script in your HTTP server application.There are two endpoints,
`/console/execute` and `/console/execute/result`. Both
accept the script as the body of a `POST` request, but the first returns a JSON response
and the second returns a plain text response.

TIP: The base path `/console` can be altered with the `console.path` configuration property.

Here is an example of a simple Groovy script:

[source,groovy]
.Example Groovy Script
----
include::{root-dir}/libs/micronaut-console/src/test/resources/com/agorapulse/micronaut/console/http/ConsoleControllerSpec/printer.groovy[]
----

You can use tools such as cURL to execute the script, or you can use IDE integrations such as the IntelliJ HTTP client.
The `Content-Type` must match the mime type of language e.g. `text/groovy`, `application/javascript`, or `text/x-kotlin`.

[source,shell script,indent=0,role="primary"]
.Bash Script
----
curl -X POST -H "Content-Type: text/groovy" --data-binary @printer.groovy "http://localhost:8080/console/execute/result"
----

[source,indent=0,role="secondary"]
.IntelliJ HTTP Client with Inline Code
----
include::{root-dir}/examples/micronaut-console-example-application/src/test/resources/inline.http[tag=request]

// language=groovy                                                                      <1>
include::{root-dir}/libs/micronaut-console/src/test/resources/com/agorapulse/micronaut/console/http/ConsoleControllerSpec/printer.groovy[]
----
<1> IntelliJ hint to treat the body of the request as Groovy code and provide content assistance

[source,indent=0,role="secondary"]
.IntelliJ HTTP Client with External Script
----
include::{root-dir}/examples/micronaut-console-example-application/src/test/resources/inline.http[tag=request]

< printer.groovy                                                                        <1>
----
<1> Path to the script file which will get all the content assist available

After execution, you will get the following results depending on an endpoint used:

[source,indent=0,role="primary"]
.Plain Text
----
include::{root-dir}/libs/micronaut-console/src/test/resources/com/agorapulse/micronaut/console/http/ConsoleControllerSpec/printer.txt[]
----

[source,json,indent=0,role="secondary"]
.JSON
----
include::{root-dir}/libs/micronaut-console/src/test/resources/com/agorapulse/micronaut/console/http/ConsoleControllerSpec/printer.json[]
----

JSON responses are useful to create a client for console endpoints. Plain text responses are useful for shell and IDE executions.

TIP: The `result` property returns a JSON representation of the last evaluated line, so it can also be a JavaScript
object or array depending on the situation.

== Security

Security is very important as you can run arbitrary code using the console. By default, the console is disabled.
You must either set `console.enabled` to `true`, or you can set `console.until`
to any ISO date in the future such as `2020-11-12T10:00:00Z`. The second option will enable the console only for the specified period.

=== Address Filter

You can specify from which address the users can access the console

[source]
.Address Filter Configuration
----
console:
include::{root-dir}/examples/micronaut-console-example-application/src/main/resources/application-secured.yml[tags=address]
----

WARNING: The addresses must start with a forward slash `/`.

WARNING: If you use a reverse proxy (e.g., Nginx on AWS Beanstalk), you must https://sergiodelamo.com/blog/host-and-ip-resolution-micronaut-load-balancer-elastic-beanstalk.html[configure hostname resolution] correctly.

=== User Filter

You can specify which users can access the console

[source]
.User FilterConfiguration
----
console:
include::{root-dir}/examples/micronaut-console-example-application/src/main/resources/application-secured.yml[tags=users]
----

You must use Micronaut Security or define your own implementation of `TypedRequestArgumentBinder<User>` to
get the username of the user.

[source,java]
.User Binder
----
include::{root-dir}/libs/micronaut-console/src/test/groovy/com/agorapulse/micronaut/console/http/SimpleUserBinder.java[lines=20..-1]
----

=== Micronaut Security Integration

Micronaut Console integrates well with the Micronaut Security library.

[source]
.Micronaut Security Configuration
----
include::{root-dir}/examples/micronaut-console-example-application/src/main/resources/application-secured.yml[tags=micronaut-security]
----
<1> Enable Micronaut Security
<2> Enable login endpoint
<3> Enable JWT token integration
<4> JWT token generator's secret
<5> Allow anonymous access for DSL files generation
<6> Allow only authenticated users execute scripts

==== Using Shell with Micronaut Security

When you are running the scripts from shell then you need to do few extra steps to authenticate with the Micronaut Security

First, create `credentials.json` file and add it to `.gitignore`.

[source,json]
.Shell Credentials File
----
include::{root-dir}/examples/micronaut-console-example-application/src/test/resources/credentials.json[]
----

Then you can create a shell script file which simplifies the console script execution:

[source,shell script]
.Shell Script `execute.sh`
----
include::{root-dir}/examples/micronaut-console-example-application/src/test/resources/execute.sh[lines=1;20..-1]
----

You can use this script to execute the console scripts:

[source,shell script]
----
./execute.sh external.groovy text/groovy http://localhost:8080
----

The mime type `text/groovy` is optional if it is the same as `text/<extension>`.

The host is optional if it is `http://localhost:8080`

==== Using IntelliJ HTTP Files with Micronaut Security

When you run the scripts from IntelliJ, you must do a few extra steps to authenticate with Micronaut Security.

First, create `http-client.private.env.json` file and add it to `.gitignore`.

[source,json]
.IntelliJ Credentials File
----
include::{root-dir}/examples/micronaut-console-example-application/src/test/resources/credentials.json[]
----

You can have as many entries for different environments (e.g., `test`) as you wish.

Then update the HTTP client file to include authentication:

[source]
.HTTP Clint file with Authentication
----
include::{root-dir}/examples/micronaut-console-example-application/src/test/resources/external.http[]
----

=== Auditing

You can audit who used the Micronaut Console by implementing a bean that implements `com.agorapulse.micronaut.console.AuditService`.
There is a default implementation which logs using SLF4J.

[source,java]
----
include::{root-dir}/libs/micronaut-console/src/main/groovy/com/agorapulse/micronaut/console/DefaultAuditService.java[lines=20..-1]
----

=== Security Advisors

You can add more customization such as role based access by implementing your own security advisor `com.agorapulse.micronaut.console.SecurityAdvisor`.

Here is how the builtin advisors look like:

.Address Advisor
[source,java]
----
include::{root-dir}/libs/micronaut-console/src/main/groovy/com/agorapulse/micronaut/console/advisors/AddressAdvisor.java[lines=20..-1]
----

.Enabled Advisor
[source,java]
----
include::{root-dir}/libs/micronaut-console/src/main/groovy/com/agorapulse/micronaut/console/advisors/EnabledAdvisor.java[lines=20..-1]
----

.Until Advisor
[source,java]
----
include::{root-dir}/libs/micronaut-console/src/main/groovy/com/agorapulse/micronaut/console/advisors/UntilAdvisor.java[lines=20..-1]
----

.Users Advisor
[source,java]
----
include::{root-dir}/libs/micronaut-console/src/main/groovy/com/agorapulse/micronaut/console/advisors/UsersAdvisor.java[lines=20..-1]
----

If any of the security advisors denies the execution then the script is not executed.

=== Compilation Customizers

Groovy programming language is the first-class citizen in Micronaut Console. You can customize the way how the Groovy script by implementing bean of type
`com.agorapulse.micronaut.console.groovy.CompilerConfigurationCustomizer`.

=== Server-side Request Forgery Protection

You may want to open your console for access only from the localhost and connect via SSH tunnel to execute the scripts. In this case, you need
to be aware of Server-side Request Forgery (SSRF). If your application
issues HTTP requests for user-defined URLs then you should protect
your console with additional required header which will be only present in
authorized calls but won't be present in any accidental ones.

[source,yaml]
----
console:
  # enable the console
  enabled: true
  # but only for localhost
  addresses:
    - /127.0.0.1
    - /0:0:0:0:0:0:0:1
  # the name of the header which needs to be present in the POST requests
  header-name: X-Console-Verify
  # the expected value of the header
  header-value: S3cr3T
----

If you configure the required header then every `POST` request must also pass the header `X-Console-Verify: S3cr3t` otherwise `403: FORBIDDEN` response will be returned from the console's endpoints.
