POST {{host}}/login
Content-Type: application/json
Accept: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

> {%
    client.global.set("auth_token", response.body.access_token);
%}

###
POST {{host}}/console/execute/result
Content-Type: text/groovy
Accept: text/plain
Authorization: Bearer {{auth_token}}

< external.groovy




