POST http://localhost:8080/login
Content-Type: application/json
Accept: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

> {%
    client.global.set("auth_token", response.body.access_token);
%}

###
# tag::request[]
POST http://localhost:8080/console/execute/result
Content-Type: text/groovy
Accept: text/plain
# end::request[]
Authorization: Bearer {{auth_token}}

# language=groovy
import com.agorapulse.micronaut.console.ConsoleEngineFactory

ctx.getBeansOfType(ConsoleEngineFactory)




