name: Manual Publish Documentation

on: workflow_dispatch

jobs:
  publish:
    name: Publish Documentation
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - name: Get Latest Release
        id: latest_version
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: agorapulse
          repo: micronaut-snitch
      - name: Publish GitHub Pages
        uses: gradle/gradle-command-action@v2
        with:
          arguments: gitPublishPush -Pversion=${{ steps.latest_version.outputs.latest_tag }}-micronaut-4.0 --stacktrace -PmicronautVersion=4.2.0 -PspockVersion=2.0-groovy-4.0 -PgroovyVersion=4.0.15 -PmicronautExampleApplicationVersion=4.2.0 -PmicronautGradlePluginVersion=4.2.0 -Dorg.ajoberstar.grgit.auth.username=${{ secrets.AGORAPULSE_BOT_PERSONAL_TOKEN }}
